// export default function Randi(){
//     return <div>
//     <div direction="rtl" class="sc-dlfnbm dCwFJp" style="animation-duration: 72s;">
//         <div class="sc-bdfBwQ cSjMpd" style="left: 0px; top: 0px;">
//         <div scale="0.75" class="sc-jrAGrp gTjcjt">
//             <div scale="0.75" class="sc-kEjbxe hnSngd">
//                 <div id="containerHeader">
//                     <div scale="0.75" class="sc-iqHYGH hercuJ">
//                         <img src="https://www.gstatic.com/stadia/gamers/avatars/xxhdpi/avatar_53.png" alt="">
//                     </div>
//                     <div scale="0.75" class="sc-dQppl cgkrjs"><p>Shubhi</p></div></div><div scale="0.75" class="sc-crrsfI euBKIE"><p>Initial college life was very fun-filled. With lots of amazing activities in college and meeting new people and getting to know them was a really nice experience. 24*7 canteen and no hostel curfew timings are really great things that make you feel free.</p></div></div></div></div><div class="sc-bdfBwQ cSjMpd" style="left: 0px; top: 0px;"><div scale="0.75" class="sc-jrAGrp gTjcjt"><div scale="0.75" class="sc-kEjbxe hnSngd"><div id="containerHeader"><div scale="0.75" class="sc-iqHYGH hercuJ"><img src="https://www.gstatic.com/stadia/gamers/avatars/xxhdpi/avatar_53.png" alt=""></div><div scale="0.75" class="sc-dQppl cgkrjs"><p>Anunay</p></div></div><div scale="0.75" class="sc-crrsfI euBKIE"><p>I was not there for induction, so all I have experienced is the horror of deadlines and evaluations.</p></div></div></div></div><div class="sc-bdfBwQ cSjMpd" style="left: 0px; top: 0px;"><div scale="0.75" class="sc-jrAGrp gTjcjt"><div scale="0.75" class="sc-kEjbxe hnSngd"><div id="containerHeader"><div scale="0.75" class="sc-iqHYGH hercuJ"><img src="https://www.gstatic.com/stadia/gamers/avatars/xxhdpi/avatar_53.png" alt=""></div><div scale="0.75" class="sc-dQppl cgkrjs"><p>Sonali</p></div></div><div scale="0.75" class="sc-crrsfI euBKIE"><p>Loved it. Loved the people, hanging out late night in groups, the induction program, huge lecture halls, the infrastructure, and the courses. It was a very new experience. I felt super independent. I could pursue what I liked, the  knew whatever I study would be meaningful.</p></div></div></div></div><div class="sc-bdfBwQ cSjMpd" style="left: 0px; top: 0px;"><div scale="0.75" class="sc-jrAGrp gTjcjt"><div scale="0.75" class="sc-kEjbxe hnSngd"><div id="containerHeader"><div scale="0.75" class="sc-iqHYGH hercuJ"><img src="https://www.gstatic.com/stadia/gamers/avatars/xxhdpi/avatar_53.png" alt=""></div><div scale="0.75" class="sc-dQppl cgkrjs"><p>Muskan</p></div></div><div scale="0.75" class="sc-crrsfI euBKIE"><p>When I first entered college I felt intimidated and like I didn't belong here, with a little anxiety about how people would be. But it took absolutely no time to shatter all my doubts and find this wonderful set of people and a room filled with opportunities. It was a different kind of environment that I was looking forward to being in.</p></div></div></div></div></div>
//     </div>
// }